package ui.swing;

import config.Config;
import engine.moves.Move;
import engine.payment.PaymentCalculator;
import engine.validation.MoveValidator;
import model.DevelopmentCard;
import model.GameState;
import model.GemColor;
import model.NobleTile;
import model.Player;

import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JEditorPane;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTextArea;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;
import javax.swing.border.TitledBorder;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.util.EnumMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Shared Swing frame infrastructure for both local and multiplayer game windows.
 *
 * <p>This base class builds the common layout, tracks UI selection state, and provides helper
 * methods for constructing pending moves from the current interaction mode.
 */
abstract class AbstractSwingSplendorFrame extends JFrame {
    protected final Config config;
    protected GameState state;
    protected final MoveValidator validator;
    protected final SwingAssetLoader assetLoader;

    protected final JLabel statusLabel = new JLabel("", SwingConstants.LEFT);
    protected final JLabel phaseLabel = new JLabel("", SwingConstants.RIGHT);
    protected final JLabel lobbyStatusLabel = new JLabel("", SwingConstants.CENTER);
    protected final JPanel marketPanel = new JPanel();
    protected final JPanel noblesPanel = new JPanel();
    protected final JTextArea logArea = new JTextArea();
    protected final JPanel playersPanel = new JPanel();
    protected final JTextArea helpArea = new JTextArea();
    protected final JPanel bankCountPanel = new JPanel(new GridLayout(6, 1, 4, 4));
    protected final Map<GemColor, JLabel> bankLabels = new EnumMap<>(GemColor.class);
    protected final Map<GemColor, JButton> tokenButtons = new EnumMap<>(GemColor.class);
    protected final Map<GemColor, ImageIcon> tokenIcons = new EnumMap<>(GemColor.class);
    protected final Map<GemColor, Integer> selectedTokenCounts = new EnumMap<>(GemColor.class);
    protected final Map<String, JButton> cardButtons = new LinkedHashMap<>();
    protected final JButton actionTakeThree = new JButton("Take 3 Different");
    protected final JButton actionTakeTwo = new JButton("Take 2 Same");
    protected final JButton actionReserve = new JButton("Reserve");
    protected final JButton actionBuy = new JButton("Buy");
    protected final JButton actionReturnTokens = new JButton("Return Tokens");
    protected final JButton actionPass = new JButton("Pass");
    protected final JButton actionCancel = new JButton("Cancel");
    protected final JButton actionConfirm = new JButton("Confirm");
    protected final JButton startGameButton = new JButton("Start Game");
    protected final DefaultListModel<DevelopmentCard> reservedModel = new DefaultListModel<>();
    protected final JList<DevelopmentCard> reservedList = new JList<>(reservedModel);
    protected final JLabel reservedLabel = new JLabel();

    protected SwingGameMode mode = SwingGameMode.IDLE;
    protected DevelopmentCard selectedBoardCard;
    protected DevelopmentCard selectedReservedCard;

    /**
     * Creates the shared frame state used by concrete Swing game windows.
     *
     * @param title window title
     * @param config application configuration
     * @param state current game state, or {@code null} before a multiplayer game starts
     * @param validator move validator used to enable and confirm actions
     */
    // Partially generated by ChatGPT-5.3; this constructor sets up the abstract swing splendor frame screen state and required services.
    protected AbstractSwingSplendorFrame(String title, Config config, GameState state, MoveValidator validator) {
        super(title);
        this.config = config;
        this.state = state;
        this.validator = validator;
        this.assetLoader = new SwingAssetLoader(config);
    }

    /**
     * Builds the common Swing layout shared by local and multiplayer views.
     *
     * @param showLobbyCenter whether the top bar should include the lobby status label
     * @param showStartButton whether the top bar should include the start-game button
     * @param playerRows number of rows to reserve for the player summary panel
     */
    // Partially generated by ChatGPT-5.3; this method builds the shared ui for the UI flow.
    protected final void buildSharedUi(boolean showLobbyCenter, boolean showStartButton, int playerRows) {
        configureFrame();
        add(buildTopBar(showLobbyCenter, showStartButton), BorderLayout.NORTH);
        add(buildBankPanel(), BorderLayout.WEST);
        JPanel center = buildMarketPanel();
        add(buildPlayersPanel(playerRows), BorderLayout.EAST);
        assembleLayout(center, buildBottomPanel());
    }

    // Generated by ChatGPT-5.3: Configures frame-level sizing, layout, and base panel grids. 
    private void configureFrame() {
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1500, 1020);
        setMinimumSize(new Dimension(1450, 980));
        setLocationRelativeTo(null);
        setLayout(new BorderLayout(10, 10));
        getContentPane().setBackground(SwingUiTheme.APP_BG);
        marketPanel.setLayout(new GridLayout(config.getNumLevels(), config.getOpenCardsPerLevel(), 10, 10));
        noblesPanel.setLayout(new GridLayout(1, Math.max(1, config.getNoblesCount(config.getMaxPlayers())), 8, 8));
    }

    // Generated by ChatGPT-5.3: Builds the top status/lobby/start-action bar. 
    private JPanel buildTopBar(boolean showLobbyCenter, boolean showStartButton) {
        JPanel topBar = new JPanel(new BorderLayout());
        topBar.setBackground(SwingUiTheme.APP_BG);
        statusLabel.setBorder(BorderFactory.createEmptyBorder(8, 10, 8, 10));
        statusLabel.setFont(statusLabel.getFont().deriveFont(java.awt.Font.BOLD, 16f));
        statusLabel.setForeground(SwingUiTheme.TEXT_PRIMARY);
        phaseLabel.setBorder(BorderFactory.createEmptyBorder(8, 10, 8, 10));
        phaseLabel.setFont(phaseLabel.getFont().deriveFont(java.awt.Font.BOLD, 14f));
        phaseLabel.setForeground(SwingUiTheme.TEXT_MUTED);
        lobbyStatusLabel.setBorder(BorderFactory.createEmptyBorder(8, 10, 8, 10));
        lobbyStatusLabel.setForeground(SwingUiTheme.TEXT_MUTED);
        SwingUiTheme.styleActionButton(startGameButton);
        startGameButton.setVisible(showStartButton);

        JPanel topRight = new JPanel(new FlowLayout(FlowLayout.RIGHT, 8, 4));
        topRight.setBackground(SwingUiTheme.APP_BG);
        topRight.add(phaseLabel);
        if (showStartButton) {
            topRight.add(startGameButton);
        }

        topBar.add(statusLabel, BorderLayout.WEST);
        if (showLobbyCenter) {
            topBar.add(lobbyStatusLabel, BorderLayout.CENTER);
        }
        topBar.add(topRight, BorderLayout.EAST);
        return topBar;
    }

    // Generated by ChatGPT-5.3: Builds the bank panel with token counts and token buttons. 
    private JPanel buildBankPanel() {
        JPanel leftBank = new JPanel(new BorderLayout(8, 8));
        leftBank.setBackground(SwingUiTheme.PANEL_BG);
        leftBank.setBorder(SwingUiTheme.createTitledBorder("Bank"));
        bankCountPanel.setBackground(SwingUiTheme.PANEL_BG);
        leftBank.add(bankCountPanel, BorderLayout.NORTH);
        JPanel tokenPanel = new JPanel(new GridLayout(3, 2, 6, 6));
        tokenPanel.setBackground(SwingUiTheme.PANEL_BG);
        for (GemColor color : GemColor.values()) {
            JButton button = new JButton(color.name());
            button.setBackground(SwingUiTheme.tokenColor(color));
            button.setContentAreaFilled(true);
            button.setOpaque(true);
            button.setForeground(color == GemColor.BLACK ? SwingUiTheme.TEXT_PRIMARY : new java.awt.Color(20, 20, 20));
            button.setBorder(new LineBorder(SwingUiTheme.BORDER_COLOR, 1, true));
            button.setPreferredSize(new Dimension(SwingUiTheme.TOKEN_BUTTON_SIZE, SwingUiTheme.TOKEN_BUTTON_SIZE));
            button.setMargin(new Insets(0, 0, 0, 0));
            button.setToolTipText("Click to select " + color.name() + " token(s)");
            ImageIcon icon = assetLoader.loadTokenIcon(color);
            if (icon != null) {
                button.setIcon(icon);
                button.setText("");
                tokenIcons.put(color, icon);
            }
            tokenButtons.put(color, button);
            selectedTokenCounts.put(color, 0);
            tokenPanel.add(button);
        }
        leftBank.add(tokenPanel, BorderLayout.CENTER);
        leftBank.setPreferredSize(new Dimension(260, 400));
        return leftBank;
    }

    // Generated by ChatGPT-5.3: Builds the center market+nobles container. 
    private JPanel buildMarketPanel() {
        JPanel center = new JPanel(new BorderLayout(8, 8));
        center.setBackground(SwingUiTheme.PANEL_BG);
        center.setBorder(SwingUiTheme.createTitledBorder("Market"));
        marketPanel.setBackground(SwingUiTheme.PANEL_BG);
        marketPanel.setPreferredSize(new Dimension(
                (SwingUiTheme.DEV_CARD_BUTTON_WIDTH * 4) + (10 * 3),
                (SwingUiTheme.DEV_CARD_BUTTON_HEIGHT * 3) + (10 * 2)
        ));
        JPanel marketWrapper = new JPanel(new GridBagLayout());
        marketWrapper.setBackground(SwingUiTheme.PANEL_BG);
        marketWrapper.add(marketPanel);
        center.add(marketWrapper, BorderLayout.CENTER);

        JPanel nobleWrap = new JPanel(new BorderLayout());
        nobleWrap.setBackground(SwingUiTheme.PANEL_BG);
        nobleWrap.setBorder(SwingUiTheme.createTitledBorder("Nobles"));
        noblesPanel.setBackground(SwingUiTheme.PANEL_BG);
        nobleWrap.add(noblesPanel, BorderLayout.CENTER);
        center.add(nobleWrap, BorderLayout.SOUTH);
        return center;
    }

    // Generated by ChatGPT-5.3: Builds the right-side players and reserved-cards section. 
    private JPanel buildPlayersPanel(int playerRows) {
        JPanel right = new JPanel(new BorderLayout(8, 8));
        right.setBackground(SwingUiTheme.PANEL_BG);
        right.setBorder(SwingUiTheme.createTitledBorder("Players"));
        playersPanel.setLayout(new GridLayout(Math.max(1, playerRows), 1, 8, 8));
        playersPanel.setBackground(SwingUiTheme.PANEL_BG);
        JScrollPane playersScroll = new JScrollPane(playersPanel);
        SwingUiTheme.styleScrollPane(playersScroll, SwingUiTheme.PANEL_BG);
        playersScroll.setPreferredSize(new Dimension(420, 400));
        right.add(playersScroll, BorderLayout.CENTER);

        reservedList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        reservedList.setBackground(SwingUiTheme.PANEL_BG_ALT);
        reservedList.setForeground(SwingUiTheme.TEXT_PRIMARY);
        reservedList.setSelectionBackground(SwingUiTheme.SELECTED_BG);
        reservedList.setSelectionForeground(SwingUiTheme.TEXT_PRIMARY);

        JPanel reservedPanel = new JPanel(new BorderLayout(4, 4));
        reservedPanel.setBackground(SwingUiTheme.PANEL_BG);
        reservedLabel.setForeground(SwingUiTheme.TEXT_PRIMARY);
        reservedPanel.add(reservedLabel, BorderLayout.NORTH);
        JScrollPane reservedScroll = new JScrollPane(reservedList);
        SwingUiTheme.styleScrollPane(reservedScroll, SwingUiTheme.PANEL_BG_ALT);
        reservedScroll.setPreferredSize(new Dimension(320, 210));
        reservedPanel.add(reservedScroll, BorderLayout.CENTER);
        right.add(reservedPanel, BorderLayout.SOUTH);
        right.setPreferredSize(new Dimension(360, 400));
        return right;
    }

    // Generated by ChatGPT-5.3: Builds the action buttons, help prompt, and log area. 
    private JPanel buildBottomPanel() {
        JPanel bottom = new JPanel(new BorderLayout(8, 8));
        bottom.setBackground(SwingUiTheme.PANEL_BG);
        JPanel actions = new JPanel(new GridLayout(1, 8, 6, 6));
        actions.setBackground(SwingUiTheme.PANEL_BG);
        actionTakeThree.setText("Take Different");
        actionTakeTwo.setText("Take " + config.getTakeSameCount() + " Same");
        actions.add(actionTakeThree);
        actions.add(actionTakeTwo);
        actions.add(actionReserve);
        actions.add(actionBuy);
        actions.add(actionReturnTokens);
        actions.add(actionPass);
        actions.add(actionCancel);
        actions.add(actionConfirm);
        bottom.add(actions, BorderLayout.NORTH);
        SwingUiTheme.styleActionButton(actionTakeThree);
        SwingUiTheme.styleActionButton(actionTakeTwo);
        SwingUiTheme.styleActionButton(actionReserve);
        SwingUiTheme.styleActionButton(actionBuy);
        SwingUiTheme.styleActionButton(actionReturnTokens);
        SwingUiTheme.styleActionButton(actionPass);
        SwingUiTheme.styleActionButton(actionCancel);
        SwingUiTheme.styleActionButton(actionConfirm);

        helpArea.setEditable(false);
        helpArea.setRows(3);
        helpArea.setLineWrap(true);
        helpArea.setWrapStyleWord(true);
        helpArea.setBackground(SwingUiTheme.PANEL_BG_ALT);
        helpArea.setForeground(SwingUiTheme.TEXT_PRIMARY);
        helpArea.setCaretColor(SwingUiTheme.TEXT_PRIMARY);
        helpArea.setBorder(SwingUiTheme.createTitledBorder("Prompt"));
        bottom.add(helpArea, BorderLayout.CENTER);

        logArea.setEditable(false);
        logArea.setRows(7);
        logArea.setBackground(SwingUiTheme.PANEL_BG_ALT);
        logArea.setForeground(SwingUiTheme.TEXT_PRIMARY);
        logArea.setCaretColor(SwingUiTheme.TEXT_PRIMARY);
        JScrollPane logScroll = new JScrollPane(logArea);
        SwingUiTheme.styleScrollPane(logScroll, SwingUiTheme.PANEL_BG_ALT);
        bottom.add(logScroll, BorderLayout.SOUTH);
        bottom.setBorder(SwingUiTheme.createTitledBorder("Actions & Log"));
        return bottom;
    }

    // Generated by ChatGPT-5.3: Assembles the center split layout into the frame. 
    private void assembleLayout(JPanel center, JPanel bottom) {
        JSplitPane centerSplit = new JSplitPane(JSplitPane.VERTICAL_SPLIT, center, bottom);
        centerSplit.setBackground(SwingUiTheme.APP_BG);
        centerSplit.setBorder(BorderFactory.createEmptyBorder());
        centerSplit.setResizeWeight(0.8);
        centerSplit.setOneTouchExpandable(true);
        centerSplit.setContinuousLayout(true);
        centerSplit.setDividerLocation(650);
        add(centerSplit, BorderLayout.CENTER);
    }

    /**
     * Binds listeners for shared buttons, token controls, and reserved-card selection.
     */
    // Partially generated by ChatGPT-5.3; this method binds UI actions to their event handlers.
    protected final void bindSharedActions() {
        actionTakeThree.addActionListener(e -> switchMode(SwingGameMode.TAKE_THREE));
        actionTakeTwo.addActionListener(e -> switchMode(SwingGameMode.TAKE_TWO));
        actionReserve.addActionListener(e -> switchMode(SwingGameMode.RESERVE));
        actionBuy.addActionListener(e -> switchMode(SwingGameMode.BUY));
        actionReturnTokens.addActionListener(e -> switchMode(SwingGameMode.RETURN_TOKENS));
        actionPass.addActionListener(e -> switchMode(SwingGameMode.PASS));
        actionCancel.addActionListener(e -> switchMode(SwingGameMode.IDLE));
        actionConfirm.addActionListener(e -> handleConfirmAction());

        for (Map.Entry<GemColor, JButton> entry : tokenButtons.entrySet()) {
            GemColor color = entry.getKey();
            JButton button = entry.getValue();
            button.addActionListener(e -> {
                onTokenButtonClicked(color);
                updateLegalUi();
            });
        }

        reservedList.addListSelectionListener(e -> {
            selectedReservedCard = reservedList.getSelectedValue();
            if (selectedReservedCard != null) {
                selectedBoardCard = null;
            }
            updateLegalUi();
        });
    }

    /**
     * Switches the current interaction mode when the concrete frame allows it.
     *
     * @param newMode requested mode
     */
    // Partially generated by ChatGPT-5.3; this method switches the UI mode for the next interaction.
    protected void switchMode(SwingGameMode newMode) {
        if (!canSwitchMode(newMode)) {
            onModeSwitchRejected(newMode);
            return;
        }
        setMode(newMode);
        updateLegalUi();
    }

    /**
     * Indicates whether a mode switch is currently allowed.
     *
     * @param newMode requested mode
     * @return {@code true} if the mode change should proceed
     */
    // Partially generated by ChatGPT-5.3; this method checks whether switching mode is allowed right now.
    protected boolean canSwitchMode(SwingGameMode newMode) {
        return true;
    }

    /**
     * Hook invoked when a requested mode switch is rejected.
     *
     * @param newMode rejected mode
     */
    // Partially generated by ChatGPT-5.3; this method responds when a mode switch is rejected.
    protected void onModeSwitchRejected(SwingGameMode newMode) {
    }

    /**
     * Clears the current interaction state and returns the UI to idle mode.
     */
    // Partially generated by ChatGPT-5.3; this method clears selection to reset the UI state.
    protected final void clearSelection() {
        setMode(SwingGameMode.IDLE);
        updateLegalUi();
    }

    // Partially generated by ChatGPT-5.3; this method handles set mode for the current game flow.
    private void setMode(SwingGameMode newMode) {
        mode = newMode;
        selectedBoardCard = null;
        selectedReservedCard = null;
        reservedList.clearSelection();
        clearTokenSelection();
    }

    /**
     * Updates the current token selection based on the active token-taking mode.
     *
     * @param color token color that was clicked
     */
    // Partially generated by ChatGPT-5.3; this method handles a token button click from the player.
    protected void onTokenButtonClicked(GemColor color) {
        if (color == GemColor.GOLD && mode != SwingGameMode.RETURN_TOKENS) {
            return;
        }
        if (mode != SwingGameMode.TAKE_THREE && mode != SwingGameMode.TAKE_TWO && mode != SwingGameMode.RETURN_TOKENS) {
            return;
        }

        int current = selectedTokenCounts.getOrDefault(color, 0);
        if (current > 0) {
            if (mode == SwingGameMode.RETURN_TOKENS) {
                int held = state == null || state.getCurrentPlayer() == null ? 0 : state.getCurrentPlayer().getTokenCount(color);
                selectedTokenCounts.put(color, current >= held ? 0 : current + 1);
            } else {
                selectedTokenCounts.put(color, 0);
            }
        } else if (mode == SwingGameMode.TAKE_TWO) {
            for (GemColor gemColor : selectedTokenCounts.keySet()) {
                selectedTokenCounts.put(gemColor, 0);
            }
            selectedTokenCounts.put(color, config.getTakeSameCount());
        } else if (mode == SwingGameMode.RETURN_TOKENS) {
            if (state != null && state.getCurrentPlayer() != null && state.getCurrentPlayer().getTokenCount(color) > 0) {
                selectedTokenCounts.put(color, 1);
            }
        } else {
            int selectedCount = (int) selectedTokenCounts.values().stream().filter(value -> value > 0).count();
            if (selectedCount < config.getTakeDifferentCount()) {
                selectedTokenCounts.put(color, 1);
            }
        }
        refreshTokenButtonLabels();
    }

    /**
     * Builds the move represented by the current UI selection.
     *
     * @return pending move, or {@code null} if the current selection is incomplete
     */
    // Partially generated by ChatGPT-5.3; this method builds the pending move for the UI flow.
    protected Move buildPendingMove() {
        if (state == null) {
            return null;
        }
        Player current = state.getCurrentPlayer();
        if (mode == SwingGameMode.TAKE_THREE) {
            Map<GemColor, Integer> tokens = selectedTokens();
            return tokens.isEmpty() ? null : Move.takeDifferent(tokens);
        }
        if (mode == SwingGameMode.TAKE_TWO) {
            Map<GemColor, Integer> selected = selectedTokens();
            if (selected.size() != 1) {
                return null;
            }
            GemColor color = selected.keySet().iterator().next();
            Map<GemColor, Integer> tokens = new EnumMap<>(GemColor.class);
            tokens.put(color, config.getTakeSameCount());
            return Move.takeSame(tokens);
        }
        if (mode == SwingGameMode.RESERVE) {
            return selectedBoardCard == null ? null : Move.reserveFaceUp(selectedBoardCard);
        }
        if (mode == SwingGameMode.BUY) {
            if (selectedBoardCard != null) {
                return Move.buy(selectedBoardCard, computePaymentTokens(current, selectedBoardCard.getCost()), false);
            }
            if (selectedReservedCard != null) {
                return Move.buy(selectedReservedCard, computePaymentTokens(current, selectedReservedCard.getCost()), true);
            }
        }
        if (mode == SwingGameMode.RETURN_TOKENS) {
            Map<GemColor, Integer> tokens = selectedTokens();
            return tokens.isEmpty() ? null : Move.returnTokens(tokens);
        }
        if (mode == SwingGameMode.PASS) {
            return Move.pass();
        }
        return null;
    }

    /**
     * Computes the payment-token breakdown that would be used for a purchase.
     *
     * @param player player attempting the purchase
     * @param cost card cost by color
     * @return token payment by color
     */
    // Partially generated by ChatGPT-5.3; this method handles compute payment tokens for the current game flow.
    protected Map<GemColor, Integer> computePaymentTokens(Player player, Map<GemColor, Integer> cost) {
        return PaymentCalculator.computePaymentTokens(player, cost);
    }

    /**
     * Returns the currently selected tokens as a sparse color-count map.
     *
     * @return selected tokens
     */
    // Partially generated by ChatGPT-5.3; this method handles selected tokens for the current game flow.
    protected Map<GemColor, Integer> selectedTokens() {
        Map<GemColor, Integer> tokens = new EnumMap<>(GemColor.class);
        for (Map.Entry<GemColor, Integer> entry : selectedTokenCounts.entrySet()) {
            if (entry.getValue() > 0) {
                tokens.put(entry.getKey(), entry.getValue());
            }
        }
        return tokens;
    }

    /**
     * Refreshes the bank token-count labels from the current game state.
     */
    // Partially generated by ChatGPT-5.3; this method refreshes the bank counts so the screen stays in sync.
    protected void refreshBankCounts() {
        if (state == null) {
            clearBankCounts();
            return;
        }
        for (GemColor color : GemColor.values()) {
            JLabel label = bankLabels.computeIfAbsent(color, ignored -> {
                JLabel created = new JLabel();
                created.setForeground(SwingUiTheme.TEXT_PRIMARY);
                bankCountPanel.add(created);
                return created;
            });
            label.setText(color.name() + ": " + state.getBank().getTokenCount(color));
        }
        bankCountPanel.revalidate();
        bankCountPanel.repaint();
    }

    /**
     * Clears the bank token-count display.
     */
    // Partially generated by ChatGPT-5.3; this method clears bank counts to reset the UI state.
    protected void clearBankCounts() {
        bankCountPanel.removeAll();
        bankLabels.clear();
        bankCountPanel.revalidate();
        bankCountPanel.repaint();
    }

    /**
     * Rebuilds the reserved-card list for the supplied player.
     *
     * @param player player whose reserved cards should be shown
     */
    // Partially generated by ChatGPT-5.3; this method refreshes the reserved cards so the screen stays in sync.
    protected void refreshReservedCards(Player player) {
        reservedModel.clear();
        if (player == null) {
            return;
        }
        for (DevelopmentCard card : player.getReservedCards()) {
            reservedModel.addElement(card);
        }
        reservedList.setCellRenderer((list, value, index, isSelected, cellHasFocus) -> {
            ImageIcon icon = assetLoader.loadCardIcon(value);
            JLabel cell;
            if (icon != null) {
                cell = new JLabel(icon);
                cell.setText("r" + (index + 1));
                cell.setHorizontalTextPosition(JLabel.CENTER);
                cell.setVerticalTextPosition(JLabel.BOTTOM);
            } else {
                cell = new JLabel("r" + (index + 1) + " | P:" + value.getPrestigePoints() + " " + value.getBonusColor()
                        + " | Cost " + value.getCost());
            }
            cell.setOpaque(true);
            cell.setForeground(SwingUiTheme.TEXT_PRIMARY);
            cell.setBackground(isSelected ? SwingUiTheme.SELECTED_BG : SwingUiTheme.PANEL_BG_ALT);
            return cell;
        });
    }

    /**
     * Rebuilds the market buttons from the current board state.
     */
    // Partially generated by ChatGPT-5.3; this method rebuilds market buttons from the latest game state.
    protected void rebuildMarketButtons() {
        if (state == null) {
            renderEmptyMarket();
            return;
        }

        renderPopulatedMarket();
    }

    // Generated by ChatGPT-5.3: Clears market UI when no game state is present. 
    private void renderEmptyMarket() {
        marketPanel.removeAll();
        cardButtons.clear();
        marketPanel.revalidate();
        marketPanel.repaint();
    }

    // Generated by ChatGPT-5.3: Re-renders market card buttons from current board state. 
    private void renderPopulatedMarket() {
        marketPanel.removeAll();
        cardButtons.clear();
        int levels = config.getNumLevels();
        int openCards = config.getOpenCardsPerLevel();
        marketPanel.setLayout(new GridLayout(levels, openCards, 10, 10));
        for (int tier = levels; tier >= 1; tier--) {
            List<DevelopmentCard> cards = state.getBoard().getFaceUpCards(tier);
            for (int col = 0; col < openCards; col++) {
                String key = "" + (char) ('a' + col) + tier;
                JButton button = createMarketButtonShell();
                if (col < cards.size()) {
                    DevelopmentCard card = cards.get(col);
                    configurePopulatedMarketButton(button, key, card);
                } else {
                    configureEmptyMarketButton(button, key);
                }
                cardButtons.put(key, button);
                marketPanel.add(button);
            }
        }
        marketPanel.revalidate();
        marketPanel.repaint();
    }

    // Generated by ChatGPT-5.3: Creates a consistently styled card button shell for market slots. 
    private JButton createMarketButtonShell() {
        JButton button = new JButton();
        button.setFocusPainted(false);
        button.setOpaque(true);
        button.setHorizontalAlignment(SwingConstants.CENTER);
        button.setVerticalAlignment(SwingConstants.CENTER);
        button.setPreferredSize(new Dimension(SwingUiTheme.DEV_CARD_BUTTON_WIDTH, SwingUiTheme.DEV_CARD_BUTTON_HEIGHT));
        button.setBorder(BorderFactory.createEmptyBorder(6, 6, 6, 6));
        return button;
    }

    // Generated by ChatGPT-5.3: Applies card visuals, tooltip, and selection behavior for an occupied market slot. 
    private void configurePopulatedMarketButton(JButton button, String key, DevelopmentCard card) {
        ImageIcon icon = assetLoader.loadCardIcon(card);
        if (icon != null) {
            button.setIcon(icon);
            button.setDisabledIcon(icon);
            button.setText("");
            button.setBackground(SwingUiTheme.SURFACE_BG);
        } else {
            button.setText(buildCardHtml(card));
            button.setBackground(SwingUiTheme.colorForBonus(card.getBonusColor()));
        }
        button.setContentAreaFilled(true);
        button.setForeground(SwingUiTheme.TEXT_PRIMARY);
        button.setBorder(new LineBorder(SwingUiTheme.BORDER_COLOR, 2));
        button.setToolTipText(buildCardTooltip(key, card));
        button.addActionListener(e -> {
            selectedBoardCard = card;
            selectedReservedCard = null;
            reservedList.clearSelection();
            updateLegalUi();
        });
    }

    // Generated by ChatGPT-5.3: Applies empty-slot visuals and disables interaction for missing cards. 
    private void configureEmptyMarketButton(JButton button, String key) {
        button.setText("<html><b>" + key + "</b><br/>Empty</html>");
        button.setBackground(SwingUiTheme.EMPTY_BG);
        button.setForeground(SwingUiTheme.TEXT_MUTED);
        button.setEnabled(false);
        button.setContentAreaFilled(true);
    }

    /**
     * Rebuilds the noble display from the current board state.
     */
    // Partially generated by ChatGPT-5.3; this method rebuilds noble cards from the latest game state.
    protected void rebuildNobleCards() {
        noblesPanel.removeAll();
        if (state == null) {
            noblesPanel.revalidate();
            noblesPanel.repaint();
            return;
        }
        List<NobleTile> nobles = state.getBoard().getAvailableNobles();
        noblesPanel.setLayout(new GridLayout(1, Math.max(1, nobles.size()), 8, 8));
        if (nobles.isEmpty()) {
            noblesPanel.add(createEmptyNobleCard());
        }
        for (int i = 0; i < nobles.size(); i++) {
            NobleTile noble = nobles.get(i);
            noblesPanel.add(createNobleCard(noble, i));
        }
        noblesPanel.revalidate();
        noblesPanel.repaint();
    }

    // Generated by ChatGPT-5.3: Creates the empty noble placeholder card. 
    private JPanel createEmptyNobleCard() {
        JPanel nobleCard = new JPanel(new BorderLayout());
        nobleCard.setBorder(new LineBorder(SwingUiTheme.BORDER_COLOR, 2));
        nobleCard.setBackground(SwingUiTheme.EMPTY_BG);
        JLabel label = new JLabel("<html><b>Empty</b></html>", SwingConstants.CENTER);
        label.setForeground(SwingUiTheme.TEXT_MUTED);
        nobleCard.add(label, BorderLayout.CENTER);
        return nobleCard;
    }

    // Generated by ChatGPT-5.3: Creates one noble card container and tooltip. 
    private JPanel createNobleCard(NobleTile noble, int index) {
        JPanel nobleCard = new JPanel(new BorderLayout());
        nobleCard.setBorder(new LineBorder(SwingUiTheme.BORDER_COLOR, 2));
        nobleCard.setBackground(SwingUiTheme.SURFACE_BG);
        nobleCard.setPreferredSize(new Dimension(SwingUiTheme.NOBLE_CARD_WIDTH, SwingUiTheme.NOBLE_CARD_HEIGHT));
        JLabel label = createNobleCardLabel(noble, index);
        nobleCard.add(label, BorderLayout.CENTER);
        nobleCard.setToolTipText("Noble " + (index + 1) + " | Prestige " + noble.getPrestigePoints()
                + " | Requirements " + noble.getRequirement().asMap());
        return nobleCard;
    }

    // Generated by ChatGPT-5.3: Creates the noble label with image fallback text rendering. 
    private JLabel createNobleCardLabel(NobleTile noble, int index) {
        ImageIcon icon = assetLoader.loadNobleIcon(noble);
        JLabel label;
        if (icon != null) {
            label = new JLabel(icon);
            label.setHorizontalAlignment(SwingConstants.CENTER);
            label.setVerticalAlignment(SwingConstants.CENTER);
        } else {
            label = new JLabel("<html><b>N" + (index + 1) + "</b><br/>P:" + noble.getPrestigePoints()
                    + "<br/>Req:" + noble.getRequirement().asMap() + "</html>");
            label.setHorizontalAlignment(SwingConstants.CENTER);
        }
        label.setBorder(BorderFactory.createEmptyBorder(6, 6, 6, 6));
        label.setForeground(SwingUiTheme.TEXT_PRIMARY);
        return label;
    }

    /**
     * Clears board-dependent panels before a multiplayer game has started.
     */
    // Partially generated by ChatGPT-5.3; this method clears pre game panels to reset the UI state.
    protected void clearPreGamePanels() {
        marketPanel.removeAll();
        marketPanel.revalidate();
        marketPanel.repaint();
        noblesPanel.removeAll();
        noblesPanel.revalidate();
        noblesPanel.repaint();
        clearBankCounts();
        reservedModel.clear();
    }

    /**
     * Enables card buttons and updates their highlight state for reserve and buy modes.
     *
     * @param current current player
     * @param allowInteractions whether interaction should be enabled at all
     * @param cardMode whether the current mode uses card selection
     */
    // Partially generated by ChatGPT-5.3; this method updates the card selection state based on current state.
    protected void updateCardSelectionState(Player current, boolean allowInteractions, boolean cardMode) {
        resetCardButtons();

        if (!allowInteractions || !cardMode || state == null || current == null) {
            return;
        }

        for (int tier = 1; tier <= config.getNumLevels(); tier++) {
            List<DevelopmentCard> cards = state.getBoard().getFaceUpCards(tier);
            for (int col = 0; col < cards.size(); col++) {
                DevelopmentCard card = cards.get(col);
                JButton button = cardButtons.get(cardKey(tier, col));
                if (button == null) {
                    continue;
                }
                updateCardButtonState(current, card, button);
            }
        }
    }

    // Generated by ChatGPT-5.3: Resets all market card buttons to disabled default styling. 
    private void resetCardButtons() {
        for (JButton button : cardButtons.values()) {
            button.setEnabled(false);
            button.setBorder(new LineBorder(SwingUiTheme.BORDER_COLOR, 2));
        }
    }

    // Generated by ChatGPT-5.3: Computes the stable market key for a tier/column slot. 
    private String cardKey(int tier, int col) {
        return "" + (char) ('a' + col) + tier;
    }

    // Generated by ChatGPT-5.3: Computes legality and applies enablement/styling for a single card button. 
    private void updateCardButtonState(Player current, DevelopmentCard card, JButton button) {
        Move move = mode == SwingGameMode.RESERVE
                ? Move.reserveFaceUp(card)
                : Move.buy(card, computePaymentTokens(current, card.getCost()), false);
        boolean legal = validator.validate(state, current, move) == null;
        button.setEnabled(legal);
        applyCardButtonBorder(button, card, legal);
    }

    // Generated by ChatGPT-5.3: Applies border styling for selected, legal-buy, and illegal-buy states. 
    private void applyCardButtonBorder(JButton button, DevelopmentCard card, boolean legal) {
        if (selectedBoardCard == card) {
            button.setBorder(new LineBorder(SwingUiTheme.ACCENT_BLUE, 4));
            return;
        }
        if (mode == SwingGameMode.BUY && legal) {
            button.setBorder(new LineBorder(SwingUiTheme.ACCENT_GREEN, 3));
            return;
        }
        if (mode == SwingGameMode.BUY) {
            button.setBorder(new LineBorder(SwingUiTheme.ACCENT_RED, 2));
        }
    }

    /**
     * Enables token buttons according to the active token-taking mode and current selection.
     *
     * @param current current player
     * @param allowInteractions whether token input should be enabled
     */
    // Partially generated by ChatGPT-5.3; this method handles apply token mode rules for the current game flow.
    protected void applyTokenModeRules(Player current, boolean allowInteractions) {
        Map<GemColor, Integer> selected = selectedTokens();
        int totalSelected = selected.values().stream().mapToInt(Integer::intValue).sum();

        for (GemColor color : GemColor.values()) {
            JButton button = tokenButtons.get(color);
            if (button == null) {
                continue;
            }
            button.setEnabled(isTokenButtonEnabled(current, allowInteractions, color, totalSelected));
        }
        refreshTokenButtonLabels();
    }

    // Generated by ChatGPT-5.3: Central token-button enablement dispatcher by mode and context. 
    private boolean isTokenButtonEnabled(Player current, boolean allowInteractions, GemColor color, int totalSelected) {
        if (!allowInteractions || color == GemColor.GOLD || state == null) {
            return false;
        }
        if (mode == SwingGameMode.TAKE_THREE) {
            return isTakeThreeTokenEnabled(color, totalSelected);
        }
        if (mode == SwingGameMode.TAKE_TWO) {
            return isTakeTwoTokenEnabled(current, color);
        }
        if (mode == SwingGameMode.RETURN_TOKENS) {
            return current != null && current.getTokenCount(color) > 0;
        }
        return false;
    }

    // Generated by ChatGPT-5.3: Checks whether a color can be selected in TAKE_THREE mode. 
    private boolean isTakeThreeTokenEnabled(GemColor color, int totalSelected) {
        return state.getBank().getTokenCount(color) > 0
                && (selectedTokenCounts.getOrDefault(color, 0) > 0 || totalSelected < config.getTakeDifferentCount());
    }

    // Generated by ChatGPT-5.3: Checks whether a TAKE_TWO preview move is legal for a color. 
    private boolean isTakeTwoTokenEnabled(Player current, GemColor color) {
        if (current == null) {
            return false;
        }
        Map<GemColor, Integer> preview = new EnumMap<>(GemColor.class);
        preview.put(color, config.getTakeSameCount());
        return validator.validate(state, current, Move.takeSame(preview)) == null;
    }

    /**
     * Refreshes token-button labels, tooltips, and selection highlighting.
     */
    // Partially generated by ChatGPT-5.3; this method refreshes the token button labels so the screen stays in sync.
    protected void refreshTokenButtonLabels() {
        for (GemColor color : GemColor.values()) {
            JButton button = tokenButtons.get(color);
            if (button == null) {
                continue;
            }
            int selected = selectedTokenCounts.getOrDefault(color, 0);
            int bank = state == null ? 0 : state.getBank().getTokenCount(color);
            if (showTokenBankCountsOnButtons() && !tokenIcons.containsKey(color)) {
                button.setText(color.name() + " (" + bank + ")" + (selected > 0 ? " x" + selected : ""));
            } else if (tokenIcons.containsKey(color)) {
                button.setText("");
            }
            button.setToolTipText(color.name() + " | bank: " + bank + " | selected: " + selected);
            button.setBackground(selected > 0 ? SwingUiTheme.SELECTED_BG : SwingUiTheme.tokenColor(color));
            button.setBorder(new LineBorder(selected > 0 ? SwingUiTheme.ACCENT_BLUE : SwingUiTheme.BORDER_COLOR, selected > 0 ? 2 : 1, true));
        }
    }

    /**
     * Indicates whether token buttons should show bank counts in their text labels.
     *
     * @return {@code true} to include bank counts in button labels
     */
    // Partially generated by ChatGPT-5.3; this method shows the token bank counts on buttons to the user.
    protected boolean showTokenBankCountsOnButtons() {
        return false;
    }

    /**
     * Clears the current token selection.
     */
    // Partially generated by ChatGPT-5.3; this method clears token selection to reset the UI state.
    protected void clearTokenSelection() {
        for (GemColor color : GemColor.values()) {
            selectedTokenCounts.put(color, 0);
        }
        refreshTokenButtonLabels();
    }

    /**
     * Indicates whether the player has at least one legal take-different move.
     *
     * @param player player to check
     * @return {@code true} if a legal move exists
     */
    // Partially generated by ChatGPT-5.3; this method checks whether any legal take-three move is available.
    protected boolean hasAnyLegalTakeThree(Player player) {
        List<GemColor> colors = List.of(GemColor.WHITE, GemColor.BLUE, GemColor.GREEN, GemColor.RED, GemColor.BLACK);
        for (int count = config.getTakeDifferentCount(); count >= 1; count--) {
            if (hasAnyLegalTakeDifferentCombination(player, colors, 0, count, new EnumMap<>(GemColor.class))) {
                return true;
            }
        }
        return false;
    }

    /**
     * Indicates whether the player has at least one legal take-two-same move.
     *
     * @param player player to check
     * @return {@code true} if a legal move exists
     */
    // Partially generated by ChatGPT-5.3; this method checks whether any legal take-two move is available.
    protected boolean hasAnyLegalTakeTwo(Player player) {
        for (GemColor color : List.of(GemColor.WHITE, GemColor.BLUE, GemColor.GREEN, GemColor.RED, GemColor.BLACK)) {
            Map<GemColor, Integer> tokens = new EnumMap<>(GemColor.class);
            tokens.put(color, config.getTakeSameCount());
            if (validator.validate(state, player, Move.takeSame(tokens)) == null) {
                return true;
            }
        }
        return false;
    }

    /**
     * Indicates whether the player can legally reserve any visible card.
     *
     * @param player player to check
     * @return {@code true} if a legal reserve move exists
     */
    // Partially generated by ChatGPT-5.3; this method checks whether any legal reserve move is available.
    protected boolean hasAnyLegalReserve(Player player) {
        for (DevelopmentCard card : state.getBoard().getFaceUpCards()) {
            if (validator.validate(state, player, Move.reserveFaceUp(card)) == null) {
                return true;
            }
        }
        return false;
    }

    /**
     * Indicates whether the player can legally buy any visible or reserved card.
     *
     * @param player player to check
     * @return {@code true} if a legal purchase exists
     */
    // Partially generated by ChatGPT-5.3; this method checks whether any legal buy move is available.
    protected boolean hasAnyLegalBuy(Player player) {
        for (DevelopmentCard card : state.getBoard().getFaceUpCards()) {
            Move move = Move.buy(card, computePaymentTokens(player, card.getCost()), false);
            if (validator.validate(state, player, move) == null) {
                return true;
            }
        }
        for (DevelopmentCard card : player.getReservedCards()) {
            Move move = Move.buy(card, computePaymentTokens(player, card.getCost()), true);
            if (validator.validate(state, player, move) == null) {
                return true;
            }
        }
        return false;
    }

    /**
     * Indicates whether the player can voluntarily return tokens as their turn.
     *
     * @param player player to check
     * @return {@code true} if a legal return move exists
     */
    protected boolean hasAnyLegalReturnTokens(Player player) {
        if (player == null || player.getTotalTokens() < config.getMaxTokensPerPlayer()) {
            return false;
        }
        for (GemColor color : GemColor.values()) {
            if (player.getTokenCount(color) <= 0) {
                continue;
            }
            Map<GemColor, Integer> tokens = new EnumMap<>(GemColor.class);
            tokens.put(color, 1);
            if (validator.validate(state, player, Move.returnTokens(tokens)) == null) {
                return true;
            }
        }
        return false;
    }

    /**
     * Creates a standard player panel shell with the configured active-state border.
     *
     * @param title panel title
     * @param active whether the player is currently active
     * @return configured player panel
     */
    // Partially generated by ChatGPT-5.3; this method creates the player panel used in the current flow.
    protected JPanel createPlayerPanel(String title, boolean active) {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBackground(SwingUiTheme.PANEL_BG_ALT);
        panel.setBorder(SwingUiTheme.createPlayerBorder(title, active));
        return panel;
    }

    /**
     * Creates a styled HTML-capable editor pane for player summaries.
     *
     * @return configured summary pane
     */
    // Partially generated by ChatGPT-5.3; this method creates the player html area used in the current flow.
    protected JEditorPane createPlayerHtmlArea() {
        JEditorPane area = new JEditorPane();
        area.setContentType("text/html");
        area.setEditable(false);
        area.putClientProperty(JEditorPane.HONOR_DISPLAY_PROPERTIES, Boolean.TRUE);
        area.setBackground(SwingUiTheme.PANEL_BG_ALT);
        area.setForeground(SwingUiTheme.TEXT_PRIMARY);
        return area;
    }

    /**
     * Returns the help text shown for the current interaction mode.
     *
     * @return prompt text for the user
     */
    // Partially generated by ChatGPT-5.3; this method handles active turn help text for the current game flow.
    protected String activeTurnHelpText() {
        return switch (mode) {
            case IDLE -> "Choose an action. Take tokens, reserve a face-up card, or buy a card.";
            case TAKE_THREE -> "Select up to " + config.getTakeDifferentCount()
                    + " different colored tokens, then confirm. If fewer than "
                    + config.getTakeDifferentCount()
                    + " colors are available and reserve, buy, and return are unavailable, 1-2 different tokens are allowed.";
            case TAKE_TWO -> "Select 1 color to take " + config.getTakeSameCount() + " tokens, then confirm.";
            case RESERVE -> "Select a face-up card to reserve, then confirm.";
            case BUY -> "Select a face-up or reserved card you can afford, then confirm.";
            case RETURN_TOKENS -> "Select one or more tokens to return to the bank. This uses your whole turn.";
            case PASS -> "Confirm to pass your turn without taking any action.";
        };
    }

    /**
     * Recursively checks whether any legal combination of distinct token colors remains.
     */
    private boolean hasAnyLegalTakeDifferentCombination(
            Player player,
            List<GemColor> colors,
            int startIndex,
            int remaining,
            Map<GemColor, Integer> selected
    ) {
        if (remaining == 0) {
            return validator.validate(state, player, Move.takeDifferent(selected)) == null;
        }

        for (int i = startIndex; i <= colors.size() - remaining; i++) {
            GemColor color = colors.get(i);
            selected.put(color, 1);
            if (hasAnyLegalTakeDifferentCombination(player, colors, i + 1, remaining - 1, selected)) {
                return true;
            }
            selected.remove(color);
        }
        return false;
    }

    /**
     * Builds fallback HTML used when card artwork is unavailable.
     *
     * @param card card to describe
     * @return HTML summary for the card button
     */
    // Partially generated by ChatGPT-5.3; this method builds the card html for the UI flow.
    protected String buildCardHtml(DevelopmentCard card) {
        StringBuilder cost = new StringBuilder();
        for (Map.Entry<GemColor, Integer> entry : card.getCost().entrySet()) {
            if (cost.length() > 0) {
                cost.append(", ");
            }
            cost.append(entry.getValue()).append(" ").append(entry.getKey().name());
        }
        return "<html><b>Card</b><br/>P:" + card.getPrestigePoints()
                + " Bonus:" + card.getBonusColor().name()
                + "<br/>Cost: " + cost + "</html>";
    }

    /**
     * Builds the tooltip text shown for a card button.
     *
     * @param key board key such as {@code a1}
     * @param card card being described
     * @return tooltip text
     */
    // Partially generated by ChatGPT-5.3; this method builds the card tooltip for the UI flow.
    protected String buildCardTooltip(String key, DevelopmentCard card) {
        return key + " | Bonus " + card.getBonusColor() + " | Prestige " + card.getPrestigePoints()
                + " | Cost " + card.getCost();
    }

    /**
     * Disables every interactive control in the shared frame.
     */
    // Partially generated by ChatGPT-5.3; this method disables input controls for a safe UI state.
    protected void disableAllInputs() {
        actionTakeThree.setEnabled(false);
        actionTakeTwo.setEnabled(false);
        actionReserve.setEnabled(false);
        actionBuy.setEnabled(false);
        actionReturnTokens.setEnabled(false);
        actionPass.setEnabled(false);
        actionCancel.setEnabled(false);
        actionConfirm.setEnabled(false);
        for (JButton button : tokenButtons.values()) {
            button.setEnabled(false);
        }
        for (JButton button : cardButtons.values()) {
            button.setEnabled(false);
        }
        reservedList.setEnabled(false);
    }

    /**
     * Appends a line to the log area and scrolls to the newest entry.
     *
     * @param message message to append
     */
    // Partially generated by ChatGPT-5.3; this method handles log for the current game flow.
    protected void log(String message) {
        logArea.append(message + "\n");
        logArea.setCaretPosition(logArea.getDocument().getLength());
    }

    /**
     * Handles confirmation of the currently selected action.
     */
    // Partially generated by ChatGPT-5.3; this method handles confirm action during gameplay.
    protected abstract void handleConfirmAction();

    /**
     * Refreshes control enablement, prompts, and selection highlighting.
     */
    // Partially generated by ChatGPT-5.3; this method updates the legal ui based on current state.
    protected abstract void updateLegalUi();
}
