package ui.swing;

import engine.moves.Move;
import engine.validation.MoveValidator;
import model.GameState;
import model.Player;
import network.GameClient;
import network.NetworkMessage;

import javax.swing.JOptionPane;
import javax.swing.JEditorPane;
import javax.swing.JPanel;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Swing UI for multiplayer over network Splendor client.
 * Connects to a GameServer and synchronizes game state.
 */
public class MultiplayerSwingApp extends AbstractSwingSplendorFrame {
    private final GameClient client;
    private final Map<Player, JPanel> playerCardPanels = new LinkedHashMap<>();
    private final Map<Player, JEditorPane> playerCardAreas = new LinkedHashMap<>();
    private int myPlayerIndex = -1;
    private int hostPlayerIndex = 0;
    private int minPlayersToStart;
    private List<String> lobbyPlayers = new ArrayList<>();
    private boolean shuttingDown = false;
    private boolean finalRoundNotified = false;

    /**
     * Creates a multiplayer game window using the default configuration.
     *
     * @param client connected multiplayer client
     */
    public MultiplayerSwingApp(GameClient client) {
        this(client, SwingConfigSupport.loadConfig());
    }

    /**
     * Internal constructor used to inject configuration for tests and alternate launchers.
     *
     * @param client connected multiplayer client
     * @param config loaded game configuration
     */
    private MultiplayerSwingApp(GameClient client, config.Config config) {
        super("Splendor Multiplayer", config, null, new MoveValidator(config));
        this.client = client;
        this.minPlayersToStart = config.getMinPlayers();

        buildSharedUi(true, true, 4);
        bindSharedActions();
        startGameButton.addActionListener(e -> onStartGame());

        new Thread(this::listenForMessages, "Splendor-Client-Listener").start();
    }

    /**
     * Starts the background receive loop that feeds server messages back onto the Swing thread.
     */
    private void listenForMessages() {
        while (client.isConnected()) {
            NetworkMessage message = client.receiveMessage();
            if (message == null) {
                break;
            }
            javax.swing.SwingUtilities.invokeLater(() -> handleMessage(message));
        }

        if (!shuttingDown) {
            javax.swing.SwingUtilities.invokeLater(() -> {
                JOptionPane.showMessageDialog(this, "Disconnected from server", "Connection Lost", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            });
        }
    }

    /**
     * Applies a received network message to the local Swing state.
     *
     * @param message message received from the server
     */
    private void handleMessage(NetworkMessage message) {
        switch (message.getType()) {
            case JOIN_ACK -> onJoinAck(message);
            case LOBBY_UPDATE -> onLobbyUpdate(message);
            case GAME_START -> onGameStart(message);
            case STATE_UPDATE -> onStateUpdate(message);
            case GAME_OVER -> onGameOver(message);
            case ERROR -> onError(message);
        }
    }

    /**
     * Handles JOIN_ACK metadata such as local player index.
     *
     * @param message JOIN_ACK payload from server
     */
    private void onJoinAck(NetworkMessage message) {
        myPlayerIndex = message.getPlayerIndex() == null ? -1 : message.getPlayerIndex();
        refreshStatus();
        updateLegalUi();
    }

    /**
     * Handles lobby updates while waiting for the host to start a match.
     *
     * @param message LOBBY_UPDATE payload from server
     */
    // Generated by ChatGPT-5.3.
    private void onLobbyUpdate(NetworkMessage message) {
        state = null;
        finalRoundNotified = false;
        lobbyPlayers = message.getPlayerNames() == null ? new ArrayList<>() : new ArrayList<>(message.getPlayerNames());
        hostPlayerIndex = message.getHostIndex() == null ? 0 : message.getHostIndex();
        minPlayersToStart = message.getMinPlayers() == null ? config.getMinPlayers() : message.getMinPlayers();
        log("Lobby updated: " + lobbyPlayers.size() + " player(s) connected.");
        refreshAll();
    }

    /**
     * Handles initial GAME_START payload and transitions UI into active gameplay state.
     *
     * @param message GAME_START payload from server
     */
    // Generated by ChatGPT-5.3.
    private void onGameStart(NetworkMessage message) {
        int previousCurrentPlayerIndex = currentPlayerIndex();
        state = message.getGameState();
        finalRoundNotified = state != null && state.isFinalRound();
        myPlayerIndex = message.getPlayerIndex();
        log("Game started! You are player " + (myPlayerIndex + 1));
        refreshAll();
        maybeShowFinalRoundNotification(false);
        maybeShowTurnPopup(previousCurrentPlayerIndex);
    }

    /**
     * Handles ongoing state snapshots pushed by the server after each move.
     *
     * @param message STATE_UPDATE payload containing latest game state
     */
    // Generated by ChatGPT-5.3.
    private void onStateUpdate(NetworkMessage message) {
        int previousCurrentPlayerIndex = currentPlayerIndex();
        boolean wasFinalRound = state != null && state.isFinalRound();
        state = message.getGameState();
        refreshAll();
        maybeShowFinalRoundNotification(wasFinalRound);
        maybeShowTurnPopup(previousCurrentPlayerIndex);
    }

    /**
     * Handles GAME_OVER payload by delegating to standard multiplayer game-over flow.
     *
     * @param message GAME_OVER payload from server
     */
    // Generated by ChatGPT-5.3.
    private void onGameOver(NetworkMessage message) {
        handleGameOver(message.getErrorMessage());
    }

    /**
     * Logs a server ERROR payload in the local event log.
     *
     * @param message ERROR payload from server
     */
    // Generated by ChatGPT-5.3.
    private void onError(NetworkMessage message) {
        log("Error: " + message.getErrorMessage());
    }

    /**
     * Handles the end-of-game prompt shown after the server reports a winner.
     *
     * @param message human-readable game-over message
     */
    private void handleGameOver(String message) {
        disableAllInputs();
        int choice = JOptionPane.showConfirmDialog(
                this,
                message + "\n\nPlay again with the same multiplayer lobby?",
                "Game Over",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE
        );

        if (choice == JOptionPane.YES_OPTION) {
            state = null;
            finalRoundNotified = false;
            clearSelection();
            refreshAll();
            if (isHost()) {
                JOptionPane.showMessageDialog(this, "The lobby has reopened. Press Start Game when everyone is ready.", "Play Again", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "The lobby has reopened. Wait for the host to start the next game.", "Play Again", JOptionPane.INFORMATION_MESSAGE);
            }
            return;
        }

        shuttingDown = true;
        client.disconnect();
        dispose();
    }

    /**
     * Refreshes all multiplayer panels based on the latest lobby or game state.
     */
    private void refreshAll() {
        if (state != null) {
            rebuildMarketButtons();
            rebuildNobleCards();
            refreshBankCounts();
            Player current = state.getCurrentPlayer();
            refreshReservedCards(current);
        } else {
            clearPreGamePanels();
        }
        refreshPlayers();
        refreshStatus();
        updateLegalUi();
    }

    /**
     * Refreshes either the pre-game lobby panels or the in-game player summaries.
     */
    private void refreshPlayers() {
        if (state == null) {
            playerCardPanels.clear();
            playerCardAreas.clear();
            SwingPlayerPanelSupport.renderLobbyPlayers(
                    this,
                    playersPanel,
                    lobbyPlayers,
                    hostPlayerIndex,
                    myPlayerIndex,
                    minPlayersToStart
            );
            return;
        }

        ensureInGamePlayerPanels();
        SwingPlayerPanelSupport.refreshSinglePlayerPanels(
                config,
                state.getCurrentPlayer(),
                playerCardPanels,
                playerCardAreas
        );
    }

    /**
     * Refreshes the status labels for either lobby or active-game mode.
     */
    private void refreshStatus() {
        if (state == null) {
            int needed = Math.max(0, minPlayersToStart - lobbyPlayers.size());
            statusLabel.setText(isHost() ? "Lobby: you are the host" : "Lobby: waiting for host");
            phaseLabel.setText(needed == 0 ? "Ready to start" : "Need " + needed + " more player" + (needed == 1 ? "" : "s"));
            lobbyStatusLabel.setText("Players connected: " + lobbyPlayers.size() + " / " + minPlayersToStart + "+");
            reservedLabel.setText("Your Reserved Cards");
            return;
        }

        Player current = state.getCurrentPlayer();
        statusLabel.setText("You: " + client.getPlayerName());
        phaseLabel.setText("Turn: " + current.getName() + (state.isFinalRound() ? " | Final Round" : ""));
        lobbyStatusLabel.setText("Turn: " + current.getName());
        reservedLabel.setText(current.getName() + " Reserved Cards");
    }

    /**
     * Indicates whether the local client may switch into the requested interaction mode.
     *
     * @param newMode requested interaction mode
     * @return true when it is the local player's turn
     */
    @Override
    protected boolean canSwitchMode(SwingInteractionMode newMode) {
        return state != null && myPlayerIndex == state.getCurrentPlayerIndex();
    }

    /**
     * Logs a short explanation when interaction is blocked.
     *
     * @param newMode rejected interaction mode
     */
    @Override
    protected void onModeSwitchRejected(SwingInteractionMode newMode) {
        if (state == null) {
            log("Game has not started yet");
        } else {
            log("Not your turn");
        }
    }

    /**
     * Validates the current selection locally and sends the resulting move to the server.
     */
    @Override
    protected void handleConfirmAction() {
        if (state == null || myPlayerIndex != state.getCurrentPlayerIndex()) {
            return;
        }

        Player current = state.getCurrentPlayer();
        Move move = buildAndValidatePendingMove(current);
        if (move == null) {
            return;
        }
        submitMove(move);
    }

    /**
     * Refreshes action availability for either the lobby state or the current multiplayer turn.
     */
    @Override
    protected void updateLegalUi() {
        boolean gameStarted = state != null;
        boolean myTurn = gameStarted && myPlayerIndex == state.getCurrentPlayerIndex();
        boolean hostCanStart = canHostStartGame(gameStarted, isHost(), lobbyPlayers.size(), minPlayersToStart);

        startGameButton.setEnabled(hostCanStart);
        startGameButton.setVisible(!gameStarted);

        if (!gameStarted) {
            updateLobbyUiState();
            return;
        }
        updateInGameUiState(myTurn);
    }

    /**
     * Applies disabled control state and lobby-specific help text before game start.
     */
    private void updateLobbyUiState() {
        disableAllInputs();
        helpArea.setText(isHost()
                ? "Wait for at least " + minPlayersToStart + " players, then press Start Game."
                : "Waiting for the host to start the game.");
    }

    /**
     * Applies in-game control enablement and status labels for the current turn owner.
     *
     * @param myTurn whether the local client owns the active turn
     */
    // Partially generated by ChatGPT-5.3.
    private void updateInGameUiState(boolean myTurn) {
        Player current = state.getCurrentPlayer();
        statusLabel.setText("You: " + client.getPlayerName());
        phaseLabel.setText("Turn: " + current.getName()
                + " | Phase: " + mode.name().replace('_', ' ')
                + (state.isFinalRound() ? " | Final Round" : ""));
        helpArea.setText(myTurn ? activeTurnHelpText() : "Wait for the other player to finish their turn.");

        actionTakeThree.setEnabled(myTurn && hasAnyLegalTakeThree(current));
        actionTakeTwo.setEnabled(myTurn && hasAnyLegalTakeTwo(current));
        actionReserve.setEnabled(myTurn && hasAnyLegalReserve(current));
        actionBuy.setEnabled(myTurn && hasAnyLegalBuy(current));
        actionReturnTokens.setEnabled(myTurn && hasAnyLegalReturnTokens(current));
        actionPass.setEnabled(myTurn);
        actionCancel.setEnabled(myTurn && mode != SwingInteractionMode.IDLE);
        reservedList.setEnabled(myTurn && mode == SwingInteractionMode.BUY);

        boolean cardMode = mode == SwingInteractionMode.RESERVE || mode == SwingInteractionMode.BUY;
        updateCardSelectionState(current, myTurn, cardMode);
        applyTokenModeRules(current, myTurn);

        Move pending = myTurn ? buildPendingMove() : null;
        actionConfirm.setEnabled(canEnableConfirm(myTurn, mode, pending, current));
    }

    /**
     * Shows a one-time final-round notification when the flag first becomes active.
     *
     * @param wasFinalRound whether final round was already active before latest update
     */
    // Partially gnerated by ChatGPT-5.3.
    private void maybeShowFinalRoundNotification(boolean wasFinalRound) {
        if (state == null || !state.isFinalRound() || wasFinalRound || finalRoundNotified) {
            return;
        }
        finalRoundNotified = true;
        String currentName = state.getCurrentPlayer().getName();
        String message = "Final round has started.\nA player reached the prestige threshold.";
        log("Final round started.");
        JOptionPane.showMessageDialog(
                this,
                message + "\nCurrent turn: " + currentName,
                "Final Round",
                JOptionPane.INFORMATION_MESSAGE
        );
    }

    /**
     * Builds and validates the currently selected move before network submission.
     *
     * @param current active player from the latest state
     * @return validated move, or null when selection is incomplete/illegal
     */
    private Move buildAndValidatePendingMove(Player current) {
        Move move = buildPendingMove();
        String pendingMessage = SingleplayerSwingApp.pendingMoveValidationMessage(move, null);
        if (pendingMessage != null) {
            log(pendingMessage);
            return null;
        }
        String error = validator.validate(state, current, move);
        String errorMessage = SingleplayerSwingApp.pendingMoveValidationMessage(move, error);
        if (errorMessage != null) {
            log(errorMessage);
            updateLegalUi();
            return null;
        }
        return move;
    }

    /**
     * Sends a previously validated move to the server and clears local selection state.
     *
     * @param move validated move to submit
     */
    private void submitMove(Move move) {
        client.sendMove(move);
        log("Sent move: " + move.getTypeName());
        clearSelection();
    }

    /**
     * Evaluates confirm-button eligibility including turn ownership and move legality.
     *
     * @param myTurn whether this client owns the active turn
     * @param mode current UI interaction mode
     * @param pending pending move candidate
     * @param current active player
     * @return true when confirm should be enabled
     */
    private boolean canEnableConfirm(boolean myTurn, SwingInteractionMode mode, Move pending, Player current) {
        if (pending == null || current == null) {
            return false;
        }
        boolean pendingLegal = validator.validate(state, current, pending) == null;
        return canConfirmMove(myTurn, mode, pendingLegal);
    }

    static boolean canHostStartGame(boolean gameStarted, boolean isHost, int lobbySize, int minPlayersToStart) {
        return !gameStarted && isHost && lobbySize >= minPlayersToStart;
    }

    static boolean canConfirmMove(boolean myTurn, SwingInteractionMode mode, boolean pendingLegal) {
        return myTurn && mode != SwingInteractionMode.IDLE && pendingLegal;
    }

    /**
     * Indicates that token buttons should include live bank counts in their labels.
     *
     * @return always true for multiplayer Swing view
     */
    @Override
    // Partially generated by ChatGPT-5.3.
    protected boolean showTokenBankCountsOnButtons() {
        return true;
    }

    /**
     * Rebuilds in-game player panels if player identity/order has changed.
     */
    private void ensureInGamePlayerPanels() {
        if (playerCardPanels.size() == state.getPlayers().size()
                && playerCardAreas.size() == state.getPlayers().size()
                && playerCardPanels.keySet().containsAll(state.getPlayers())
                && playerCardAreas.keySet().containsAll(state.getPlayers())) {
            return;
        }

        SwingPlayerPanelSupport.initialiseSinglePlayerPanels(
                this,
                playersPanel,
                state,
                playerCardPanels,
                playerCardAreas
        );
    }

    /**
     * Sends a start-game request when the local client is the host and the lobby is ready.
     */
    private void onStartGame() {
        if (state != null) {
            return;
        }
        if (!isHost()) {
            log("Only the server creator can start the game.");
            return;
        }
        if (lobbyPlayers.size() < minPlayersToStart) {
            log("Need at least " + minPlayersToStart + " players to start.");
            return;
        }
        client.sendStartRequest();
        log("Start request sent.");
    }

    /**
     * Indicates whether the local client is currently the lobby host.
     *
     * @return true when the local player is the host
     */
    private boolean isHost() {
        return myPlayerIndex >= 0 && myPlayerIndex == hostPlayerIndex;
    }

    /**
     * Returns the current player index from the latest state snapshot.
     *
     * @return current player index, or -1 if no game is active
     */
    private int currentPlayerIndex() {
        return state == null ? -1 : state.getCurrentPlayerIndex();
    }

    /**
     * Shows a popup when control passes to the local player.
     *
     * @param previousCurrentPlayerIndex player whose turn it was before the latest update
     */
    private void maybeShowTurnPopup(int previousCurrentPlayerIndex) {
        if (state == null || myPlayerIndex < 0) {
            return;
        }

        int currentPlayerIndex = state.getCurrentPlayerIndex();
        if (currentPlayerIndex == myPlayerIndex && previousCurrentPlayerIndex != myPlayerIndex) {
            String currentPlayerName = state.getCurrentPlayer().getName();
            JOptionPane.showMessageDialog(
                    this,
                    "It's your turn, " + currentPlayerName + ".",
                    "Your Turn",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }
}
