package ui.swing;

import config.Config;
import config.ConfigSupport;

/**
 * Small facade for loading the configuration used by Swing entry points.
 */
final class SwingConfigSupport {
    // Partially generated by ChatGPT-5.3; this constructor sets up the swing config support screen state and required services.
    private SwingConfigSupport() {
    }

    /**
     * Loads the default configuration for Swing applications.
     *
     * @return loaded or fallback configuration
     */
    // Partially generated by ChatGPT-5.3; this method loads the config needed by the UI.
    static Config loadConfig() {
        return ConfigSupport.loadDefaultConfig();
    }
}
