import network.ClientMain;
import config.ConfigSupport;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.awt.GraphicsEnvironment;

/**
 * Launcher that lets the user choose between single-player and multiplayer modes.
 */
public class Main {
    /**
     * this shows the game-mode selection(single player, multiplayer) for our app
     *
     */
    // Partially generated by ChatGPT-5.3; this method starts the app and opens the first UI flow.
    public static void main(String[] args) {
        if (GraphicsEnvironment.isHeadless()) {
            System.err.println("Splendor requires a graphical desktop environment to launch the Swing UI.");
            System.exit(1);
            return;
        }

        // this is to invoke the showModeDialog function on the Event Dispatch Thread which is required for swing GUI, to prevent unexpected crashes 
        SwingUtilities.invokeLater(Main::showModeDialog);
    }

    /**
     * Prompts the user to launch single-player or multiplayer mode.
     */
    private static void showModeDialog() {
        while (true) {
            String[] options = {"Single Player", "Multiplayer", "Exit"};
            int selected = showOptionDialog("Choose game mode", "Splendor", options);

            switch (selected) {
                case 0 -> {
                    ui.swing.SwingSplendorApp app = new ui.swing.SwingSplendorApp();
                    app.setVisible(true);
                    return;
                }
                case 1 -> {
                    if (showMultiplayerModeDialog()) {
                        return;
                    }
                }
                case 2 -> {
                    System.exit(0);
                    return;
                }
                default -> {
                    System.exit(0);
                    return;
                }
            }
        }
    }

    /**
     * Shows multiplayer mode choices.
     *
     * @return {@code true} when a game flow is launched; {@code false} when user goes back
     */
    // Partially generated by ChatGPT-5.3; this method shows the multiplayer mode dialog to the user.
    private static boolean showMultiplayerModeDialog() {
        while (true) {
            String[] options = {"Multiplayer over Network", "Multiplayer on Same Laptop", "Back"};
            int selected = showOptionDialog("Choose multiplayer mode", "Multiplayer", options);

            switch (selected) {
                case 0 -> {
                    if (showNetworkModeDialog()) {
                        return true;
                    }
                }
                case 1 -> {
                    launchSameLaptopMultiplayer();
                    return true;
                }
                case 2 -> {
                    return false;
                }
                default -> {
                    System.exit(0);
                    return true;
                }
            }
        }
    }

    /**
     * Shows host/join options for network multiplayer.
     *
     * @return {@code true} when a network flow is launched; {@code false} when user goes back
     */
    // Partially Assisted by ChatGPT-5.3; this method shows the network mode dialog to the user. 
    private static boolean showNetworkModeDialog() {
        while (true) {
            String[] options = {"Host Server", "Join Server", "Back"};
            int selected = showOptionDialog("Choose network mode", "Multiplayer over Network", options);

            switch (selected) {
                case 0 -> {
                    ClientMain.showHostConnectionDialog();
                    return true;
                }
                case 1 -> {
                    ClientMain.showConnectionDialog();
                    return true;
                }
                case 2 -> {
                    return false;
                }
                default -> {
                    System.exit(0);
                    return true;
                }
            }
        }
    }

    /**
     * Prompts for same-laptop player count and launches a local all-human game.
     */
    // Partially generated by ChatGPT-5.3; this method handles launch same laptop multiplayer for the current game flow.
    private static void launchSameLaptopMultiplayer() {
        config.Config config = ConfigSupport.loadDefaultConfig();
        int minPlayers = config.getMinPlayers();
        int maxPlayers = config.getMaxPlayers();

        Object[] options = new Object[maxPlayers - minPlayers + 1];
        for (int i = minPlayers; i <= maxPlayers; i++) {
            options[i - minPlayers] = String.valueOf(i);
        }

        Object selected = JOptionPane.showInputDialog(
                null,
                "How many players will use this laptop?",
                "Multiplayer on Same Laptop",
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]
        );

        if (selected == null) {
            System.exit(0);
            return;
        }

        try {
            int playerCount = Integer.parseInt(selected.toString());
            ui.swing.SwingSplendorApp app = new ui.swing.SwingSplendorApp(playerCount);
            app.setVisible(true);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid player count: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Partially generated by ChatGPT-5.3; this method shows the option dialog to the user.
    private static int showOptionDialog(String message, String title, String[] options) {
        return JOptionPane.showOptionDialog(
                null,
                message,
                title,
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.PLAIN_MESSAGE,
                null,
                options,
                options[0]
        );
    }
}
