package network;

import ui.swing.MultiplayerSwingApp;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;

/**
 * Launches the multiplayer client flow.
 *
 * This class is responsible only for the small startup UI where the
 * player chooses a host, port, and display name before the main
 * multiplayer Swing screen opens.
 */
public class ClientMain {
    private static final String DEFAULT_HOST = "localhost";
    private static final String DEFAULT_PORT = "12345";
    private static final int SERVER_BOOT_WAIT_MILLIS = 200;

    /**
     * Starts the client UI on Swing's event thread so all later dialog
     * work happens on the correct thread.
     *
     * @param args ignored command-line arguments
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            showConnectionDialog();
        });
    }

    /**
     * Opens the normal join dialog using the default local host and port.
     */
    public static void showConnectionDialog() {
        showConnectionDialog(DEFAULT_HOST, DEFAULT_PORT, false);
    }

    /**
     * Opens the host flow, which starts a local server first and then
     * connects the same machine to it as a client.
     */
    // Generated by ChatGPT-5.3.
    public static void showHostConnectionDialog() {
        showConnectionDialog(DEFAULT_HOST, DEFAULT_PORT, true);
    }

    /**
     * Opens the connection dialog with pre-filled host and port values.
     *
     * @param defaultHost default host name or IP address
     * @param defaultPort default port text shown in the form
     */
    public static void showConnectionDialog(
            String defaultHost,
            String defaultPort
    ) {
        showConnectionDialog(defaultHost, defaultPort, false);
    }

    // Generated by ChatGPT-5.3.
    private static void showConnectionDialog(
            String defaultHost,
            String defaultPort,
            boolean hostMode
    ) {
        JFrame dialog = createConnectionFrame();
        JPanel panel = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = createDefaultConstraints();

        JTextField hostField = addLabeledField(
                panel,
                gbc,
                0,
                "Host IP:",
                defaultHost
        );
        JTextField portField = addLabeledField(
                panel,
                gbc,
                1,
                "Port:",
                defaultPort
        );
        JTextField nameField = addLabeledField(
                panel,
                gbc,
                2,
                "Your Name:",
                "Player"
        );

        JButton connectButton = addConnectButton(panel, gbc);
        connectButton.addActionListener(e ->
                attemptConnection(dialog, hostField, portField, nameField, hostMode)
        );

        dialog.add(panel);
        dialog.setVisible(true);
    }

    // Generated by ChatGPT-5.3.
    private static void startLocalServer(int port, JFrame parent) {
        Thread serverThread = new Thread(() -> {
            try {
                new GameServer(port).start();
            } catch (Exception e) {
                // Server startup happens on a background thread, so any
                // UI error message must be posted back onto Swing's thread.
                SwingUtilities.invokeLater(() ->
                        JOptionPane.showMessageDialog(
                                parent,
                                "Failed to start server: " + e.getMessage(),
                                "Error",
                                JOptionPane.ERROR_MESSAGE
                        )
                );
            }
        }, "Splendor-Server");
        serverThread.setDaemon(true);
        serverThread.start();

        try {
            Thread.sleep(SERVER_BOOT_WAIT_MILLIS);
        } catch (InterruptedException ignored) {
            Thread.currentThread().interrupt();
        }
    }

    private static JFrame createConnectionFrame() {
        JFrame dialog = new JFrame("Connect to Splendor Game");
        dialog.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        dialog.setSize(400, 200);
        dialog.setLocationRelativeTo(null);
        return dialog;
    }

    private static GridBagConstraints createDefaultConstraints() {
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);
        return gbc;
    }

    private static JTextField addLabeledField(
            JPanel panel,
            GridBagConstraints gbc,
            int row,
            String label,
            String defaultValue
    ) {
        gbc.gridx = 0;
        gbc.gridy = row;
        panel.add(new JLabel(label), gbc);

        gbc.gridx = 1;
        JTextField field = new JTextField(defaultValue, 15);
        panel.add(field, gbc);
        return field;
    }

    private static JButton addConnectButton(
            JPanel panel,
            GridBagConstraints gbc
    ) {
        JButton connectButton = new JButton("Connect");
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        panel.add(connectButton, gbc);
        return connectButton;
    }

    private static void attemptConnection(
            JFrame dialog,
            JTextField hostField,
            JTextField portField,
            JTextField nameField,
            boolean hostMode
    ) {
        String host = hostField.getText().trim();
        String portText = portField.getText().trim();
        String name = nameField.getText().trim();

        if (!hasCompleteForm(host, portText, name)) {
            showError(dialog, "Please fill all fields", "Error");
            return;
        }

        try {
            int port = Integer.parseInt(portText);
            connectUsingFormValues(dialog, host, port, name, hostMode);
        } catch (NumberFormatException ex) {
            showError(dialog, "Invalid port number", "Error");
        }
    }

    private static boolean hasCompleteForm(
            String host,
            String portText,
            String name
    ) {
        return !host.isEmpty() && !portText.isEmpty() && !name.isEmpty();
    }

    private static void connectUsingFormValues(
            JFrame dialog,
            String host,
            int port,
            String name,
            boolean hostMode
    ) {
        if (hostMode) {
            startLocalServer(port, dialog);
        }

        GameClient client = new GameClient(host, port, name);
        if (client.connect()) {
            launchMultiplayerWindow(dialog, client);
            return;
        }

        showError(dialog, "Failed to connect to server", "Connection Error");
    }

    private static void launchMultiplayerWindow(
            JFrame dialog,
            GameClient client
    ) {
        dialog.dispose();
        new MultiplayerSwingApp(client).setVisible(true);
    }

    private static void showError(
            JFrame parent,
            String message,
            String title
    ) {
        JOptionPane.showMessageDialog(
                parent,
                message,
                title,
                JOptionPane.ERROR_MESSAGE
        );
    }
}
