package network;

import ui.swing.MultiplayerSwingApp;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;

/**
 * Launches the multiplayer client flow.
 *
 * This class is responsible only for the small startup UI where the
 * player chooses a host, port, and display name before the main
 * multiplayer Swing screen opens.
 */
public class ClientMain {
    /**
     * Starts the client UI on Swing's event thread so all later dialog
     * work happens on the correct thread.
     *
     * @param args ignored command-line arguments
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            showConnectionDialog();
        });
    }

    /**
     * Opens the normal join dialog using the default local host and port.
     */
    public static void showConnectionDialog() {
        showConnectionDialog("localhost", "12345", false);
    }

    /**
     * Opens the host flow, which starts a local server first and then
     * connects the same machine to it as a client.
     */
    // Generated by ChatGPT-5.3.
    public static void showHostConnectionDialog() {
        showConnectionDialog("localhost", "12345", true);
    }

    /**
     * Opens the connection dialog with pre-filled host and port values.
     *
     * @param defaultHost default host name or IP address
     * @param defaultPort default port text shown in the form
     */
    public static void showConnectionDialog(
            String defaultHost,
            String defaultPort
    ) {
        showConnectionDialog(defaultHost, defaultPort, false);
    }

    // Generated by ChatGPT-5.3.
    private static void showConnectionDialog(
            String defaultHost,
            String defaultPort,
            boolean hostMode
    ) {
        // Build a small form that collects connection details before we
        // create a real network client.
        JFrame dialog = new JFrame("Connect to Splendor Game");
        dialog.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        dialog.setSize(400, 200);
        dialog.setLocationRelativeTo(null);

        JPanel panel = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);

        gbc.gridx = 0;
        gbc.gridy = 0;
        panel.add(new JLabel("Host IP:"), gbc);
        gbc.gridx = 1;
        JTextField hostField = new JTextField(defaultHost, 15);
        panel.add(hostField, gbc);

        gbc.gridx = 0;
        gbc.gridy = 1;
        panel.add(new JLabel("Port:"), gbc);
        gbc.gridx = 1;
        JTextField portField = new JTextField(defaultPort, 15);
        panel.add(portField, gbc);

        gbc.gridx = 0;
        gbc.gridy = 2;
        panel.add(new JLabel("Your Name:"), gbc);
        gbc.gridx = 1;
        JTextField nameField = new JTextField("Player", 15);
        panel.add(nameField, gbc);

        JButton connectButton = new JButton("Connect");
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        panel.add(connectButton, gbc);

        connectButton.addActionListener(e -> {
            // Read and sanitize the form input before trying to connect.
            String host = hostField.getText().trim();
            String portStr = portField.getText().trim();
            String name = nameField.getText().trim();

            if (host.isEmpty() || portStr.isEmpty() || name.isEmpty()) {
                JOptionPane.showMessageDialog(
                        dialog,
                        "Please fill all fields",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            try {
                int port = Integer.parseInt(portStr);
                if (hostMode) {
                    // In host mode we boot a local server first, then
                    // connect the client to that new server.
                    startLocalServer(port, dialog);
                }
                GameClient client = new GameClient(host, port, name);
                if (client.connect()) {
                    // The network connection succeeded, so we can replace
                    // the setup dialog with the actual game window.
                    dialog.dispose();
                    new MultiplayerSwingApp(client).setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(
                            dialog,
                            "Failed to connect to server",
                            "Connection Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(
                        dialog,
                        "Invalid port number",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        });

        dialog.add(panel);
        dialog.setVisible(true);
    }

    // Generated by ChatGPT-5.3.
    private static void startLocalServer(int port, JFrame parent) {
        Thread serverThread = new Thread(() -> {
            try {
                new GameServer(port).start();
            } catch (Exception e) {
                // Server startup happens on a background thread, so any
                // UI error message must be posted back onto Swing's thread.
                SwingUtilities.invokeLater(() ->
                        JOptionPane.showMessageDialog(
                                parent,
                                "Failed to start server: " + e.getMessage(),
                                "Error",
                                JOptionPane.ERROR_MESSAGE
                        )
                );
            }
        }, "Splendor-Server");
        serverThread.setDaemon(true);
        serverThread.start();

        try {
            // Give the server thread a moment (200ms) to bind before
            // the local client connects.
            Thread.sleep(200);
        } catch (InterruptedException ignored) {
            Thread.currentThread().interrupt();
        }
    }
}
