package network;

import engine.moves.Move;
import model.GameState;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;

/**
 * Small client-side wrapper around the multiplayer socket connection.
 *
 * The Swing UI uses this class as its networking bridge. It hides
 * the raw socket and object streams and gives the UI a simpler API for
 * connecting, sending requests, and receiving server updates.
 */
public class GameClient {
    private final String host;
    private final int port;
    private final String playerName;
    private Socket socket;
    private ObjectInputStream in;
    private ObjectOutputStream out;
    private GameState currentState;
    private int myPlayerIndex = -1;
    private volatile boolean connected = false;

    /**
     * Creates a client object that knows where to connect and which
     * player name to announce after connecting.
     *
     * @param host server host name or IP address
     * @param port server port
     * @param playerName player name announced to the server when joining
     */
    public GameClient(String host, int port, String playerName) {
        this.host = host;
        this.port = port;
        this.playerName = playerName;
    }

    /**
     * Opens the socket connection and immediately sends the JOIN
     * message that introduces this player to the server.
     *
     * @return true if the connection was established successfully
     */
    // Generated by ChatGPT-5.3: Opens a connection to send join message and manage exceptions
    public boolean connect() {
        try {
            // The client opens the same pair of object streams the server
            // expects, then sends a JOIN message as the first protocol step.
            socket = new Socket(host, port);
            out = new ObjectOutputStream(socket.getOutputStream());
            in = new ObjectInputStream(socket.getInputStream());

            out.writeObject(NetworkMessage.join(playerName));
            out.flush();

            connected = true;
            return true;
        } catch (IOException e) {
            System.err.println("Failed to connect: " + e.getMessage());
            return false;
        }
    }

    /**
     * Closes the connection after trying to send a polite DISCONNECT
     * message first.
     */
    public void disconnect() {
        connected = false;
        try {
            if (out != null) {
                out.writeObject(NetworkMessage.disconnect());
                out.flush();
            }
            if (socket != null) {
                socket.close();
            }
        } catch (IOException e) {
            // Best-effort shutdown: the socket may already be closed
            // or unreachable.
        }
    }

    /**
     * Sends the local player's chosen move to the server.
     *
     * @param move move selected by the local player
     */
    public void sendMove(Move move) {
        sendMessage(NetworkMessage.move(move), "move");
    }

    /**
     * Asks the host-controlled server to start the current lobby.
     */
    public void sendStartRequest() {
        sendMessage(NetworkMessage.startRequest(), "start request");
    }

    /**
     * Waits for the next message from the server.
     *
     * The Swing layer usually calls this from a background thread so
     * waiting for network traffic does not freeze the UI.
     *
     * @return the received message, or null if the connection fails
     */
    public NetworkMessage receiveMessage() {
        if (!connected) {
            return null;
        }
        try {
            return (NetworkMessage) in.readObject();
        } catch (IOException | ClassNotFoundException e) {
            System.err.println("Failed to receive message: " + e.getMessage());
            connected = false;
            return null;
        }
    }

    /**
     * Indicates whether this wrapper still believes the connection is
     * usable.
     *
     * @return true if the client is connected
     */
    public boolean isConnected() {
        return connected;
    }

    /**
     * Returns the latest game state snapshot cached by the UI layer.
     *
     * @return latest cached game state, or null if none has
     *     been stored
     */
    public GameState getCurrentState() {
        return currentState;
    }

    /**
     * Returns the player index the server assigned to this client.
     *
     * @return zero-based player index, or -1 if not assigned yet
     */
    public int getMyPlayerIndex() {
        return myPlayerIndex;
    }

    /**
     * Returns the player name this client joined with.
     *
     * @return player name announced during join
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * Stores the latest full game snapshot received from the server.
     *
     * @param state latest game state
     */
    public void setCurrentState(GameState state) {
        this.currentState = state;
    }

    /**
     * Records the player index assigned by the server after joining.
     *
     * @param index zero-based player index
     */
    public void setMyPlayerIndex(int index) {
        this.myPlayerIndex = index;
    }

    private void sendMessage(NetworkMessage message, String actionName) {
        if (!connected) {
            return;
        }
        try {
            // All outbound requests use the same helper so connection
            // failure handling stays consistent in one place.
            out.writeObject(message);
            out.flush();
        } catch (IOException e) {
            System.err.println(
                    "Failed to send " + actionName + ": " + e.getMessage()
            );
            connected = false;
        }
    }
}
