package network;

import config.Config;
import config.ConfigSupport;
import engine.moves.Move;
import engine.turn.MoveExecutor;
import engine.turn.NobleAssigner;
import engine.turn.TurnManager;
import engine.turn.TurnPostProcessor;
import engine.turn.TurnProgressionService;
import engine.turn.TurnResolutionResult;
import engine.turn.TurnResolutionService;
import engine.turn.WinnerChecker;
import engine.validation.MoveValidator;
import model.GameState;
import model.NobleTile;
import model.Player;
import setup.GameStateFactory;

import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/**
 * Hosts a multiplayer Splendor lobby and, once started, the live game.
 *
 * This class is the central coordinator for network play. It owns
 * the shared GameState and the engine services used to validate and
 * apply each move. Lobby bookkeeping and repeated outbound messaging
 * are delegated to small helper classes.
 */
public class GameServer {
    private final Config config = buildConfig();
    private final int port;
    private ServerSocket serverSocket;
    private final LobbyManager lobbyManager = new LobbyManager(config);
    private final ServerBroadcaster broadcaster =
            new ServerBroadcaster(config, lobbyManager);
    private GameState gameState;
    private boolean gameStarted = false;
    private final MoveValidator validator = new MoveValidator(config);
    private final MoveExecutor executor = new MoveExecutor(config);
    private final NobleAssigner nobleAssigner = new NobleAssigner();
    private final TurnPostProcessor turnPostProcessor =
            new TurnPostProcessor(config, nobleAssigner);
    private final WinnerChecker winnerChecker = new WinnerChecker(config);
    private final TurnManager turnManager = new TurnManager();
    private final TurnProgressionService turnProgressionService =
            new TurnProgressionService();
    private final TurnResolutionService turnResolutionService =
            new TurnResolutionService(
                    validator,
                    executor,
                    turnPostProcessor,
                    winnerChecker,
                    turnManager,
                    turnProgressionService
            );

    /**
     * Creates a server that listens on the supplied port.
     *
     * @param port TCP port to bind
     */
    public GameServer(int port) {
        this.port = port;
    }

    /**
     * Loads the server's rule configuration from the normal config source.
     */
    private static Config buildConfig() {
        return ConfigSupport.loadDefaultConfig();
    }

    /**
     * Opens the server socket and keeps accepting players into the
     * lobby until a game has started.
     *
     * @throws IOException if the server socket cannot be opened or
     *     accepted from
     */
    // Generated by ChatGPT-5.3: to accept client connections and manage exceptions and cases
    public void start() throws IOException {
        serverSocket = new ServerSocket(port);
        announceServerStartup();

        ExecutorService executor = Executors.newCachedThreadPool();
        while (!gameStarted) {
            acceptOneClient(executor);
        }
    }

    /**
     * Creates a fresh game for the players currently waiting in the lobby
     * and sends the starting state to each client.
     */
    // Generated by ChatGPT-5.3: Generates a new game in the current lobby
    private void startGame() {
        logGameStartAttempt();

        List<Player> players = lobbyManager.buildPlayers();

        try {
            gameState = createServerGameState(players);
        } catch (RuntimeException e) {
            System.err.println("Failed to initialize game: " + e.getMessage());
            return;
        }

        gameStarted = true;
        lobbyManager.assignPlayerIndexes();
        sendGameStartMessages();
        System.out.println("Game started!");
    }

    /**
     * Handles a request to start the current lobby.
     *
     * Only the first connected client acts as the host, and the game
     * can start only after the minimum player count has been reached.
     *
     * @param client client that sent the request
     */
    public synchronized void handleStartRequest(ClientHandler client) {
        String startError = validateStartRequest(client);
        if (startError != null) {
            client.sendMessage(NetworkMessage.error(startError));
            if (!lobbyManager.hasMinimumPlayers()) {
                broadcaster.broadcastLobbyState();
            }
            return;
        }

        System.out.println("Host requested start. Starting game...");
        startGame();
    }

    /**
     * Finalizes a successful join and then sends everyone the updated
     * lobby roster.
     *
     * @param client client that completed the join handshake
     */
    public synchronized void handleJoin(ClientHandler client) {
        int lobbyIndex = lobbyManager.indexOf(client);
        if (lobbyIndex < 0) {
            return;
        }
        client.sendMessage(NetworkMessage.joinAck(lobbyIndex));
        broadcaster.broadcastLobbyState();
    }

    /**
     * Handles one move request from a connected player.
     *
     * This method checks that the game is live, verifies that the
     * sender is the current player, asks the engine to resolve the turn,
     * and then broadcasts the resulting state or error.
     *
     * @param client client that sent the move
     * @param move requested move
     */
    public synchronized void handleMove(ClientHandler client, Move move) {
        String moveError = validateMoveRequest(client);
        if (moveError != null) {
            client.sendMessage(NetworkMessage.error(moveError));
            return;
        }

        Player currentPlayer = gameState.getCurrentPlayer();
        TurnResolutionResult turnResult = resolvePlayerMove(currentPlayer, move);
        if (!turnResult.isSuccess()) {
            client.sendMessage(
                    NetworkMessage.error(turnResult.getValidationError())
            );
            return;
        }

        logTurnOutcome(currentPlayer, turnResult);
        if (handleCompletedGameIfNeeded(turnResult)) {
            return;
        }

        broadcaster.broadcastState(gameState);
    }

    /**
     * Writes the notable results of a resolved turn to the server log.
     */
    private void logTurnOutcome(
            Player player,
            TurnResolutionResult turnResult
    ) {
        if (!turnResult.getDiscardedTokens().isEmpty()) {
            System.out.println(
                    player.getName() + " discarded "
                            + turnResult.getDiscardedTokens()
            );
        }
        for (NobleTile noble : turnResult.getAssignedNobles()) {
            System.out.println(
                    player.getName() + " attracted noble: " + noble
            );
        }
        if (turnResult.isFinalRoundTriggered()) {
            System.out.println("Final round triggered by " + player.getName());
        }
    }

    /**
     * Removes a disconnected client from the server's client list.
     *
     * If the game has not started yet, the lobby view is refreshed so
     * the remaining clients can see the updated player list.
     *
     * @param client disconnected client
     */
    public synchronized void removeClient(ClientHandler client) {
        lobbyManager.removeClient(client);
        logDisconnect();
        refreshLobbyIfWaiting();
        shutDownIfLobbyIsEmpty();
    }

    /**
     * Starts a standalone multiplayer server from the command line.
     *
     * @param args optional first argument specifying the listening port
     */
    public static void main(String[] args) {
        int port = 12345;
        if (args.length > 0) {
            try {
                port = Integer.parseInt(args[0]);
            } catch (NumberFormatException e) {
                System.err.println("Invalid port number: " + args[0]);
                return;
            }
        }

        GameServer server = new GameServer(port);
        try {
            server.start();
        } catch (IOException e) {
            System.err.println("Server error: " + e.getMessage());
        }
    }
    
    private void announceServerStartup() {
        System.out.println("Server started on port " + port);
        System.out.println("Waiting for players to join...");
    }

    private void acceptOneClient(ExecutorService executor) throws IOException {
        Socket clientSocket = serverSocket.accept();
        if (lobbyIsFull()) {
            rejectExtraClient(clientSocket);
            return;
        }

        ClientHandler handler = new ClientHandler(clientSocket, this);
        registerClient(handler);
        executor.submit(handler);
    }

    private boolean lobbyIsFull() {
        return !lobbyManager.canAcceptMoreClients();
    }

    private void rejectExtraClient(Socket clientSocket) {
        broadcaster.rejectConnection(
                clientSocket,
                "Lobby is full (max " + config.getMaxPlayers() + " players)"
        );
    }

    private void registerClient(ClientHandler handler) {
        lobbyManager.addClient(handler);
        System.out.println(
                "Player joined. Total players: "
                        + lobbyManager.getClientCount()
        );
    }

    private void logGameStartAttempt() {
        System.out.println(
                "Starting game with " + lobbyManager.getClientCount()
                        + " players"
        );
    }

    private GameState createServerGameState(List<Player> players) {
        return new GameStateFactory(
                config,
                GameStateFactory.FallbackProfile.SERVER
        ).createGame(players, message -> System.err.println(message));
    }

    private void sendGameStartMessages() {
        List<ClientHandler> clients = lobbyManager.getClients();
        for (int i = 0; i < clients.size(); i++) {
            sendGameStartMessage(clients.get(i), i);
        }
    }

    private void sendGameStartMessage(ClientHandler client, int playerIndex) {
        client.sendMessage(NetworkMessage.gameStart(gameState, playerIndex));
    }

    private String validateStartRequest(ClientHandler client) {
        if (gameStarted) {
            return "Game already started";
        }
        if (!lobbyManager.isHost(client)) {
            return "Only host can start the game";
        }
        if (!lobbyManager.hasMinimumPlayers()) {
            return "Need at least " + config.getMinPlayers()
                    + " players to start";
        }
        return null;
    }

    private String validateMoveRequest(ClientHandler client) {
        if (!isGameRunning()) {
            return "Game not started";
        }

        return validateTurnOwnership(client);
    }

    private boolean isGameRunning() {
        return gameStarted && gameState != null;
    }

    private String validateTurnOwnership(ClientHandler client) {
        int playerIndex = client.getPlayerIndex();
        if (playerIndex != gameState.getCurrentPlayerIndex()) {
            return "Not your turn";
        }
        return null;
    }

    private TurnResolutionResult resolvePlayerMove(Player player, Move move) {
        return turnResolutionService.resolveTurn(gameState, player, move);
    }

    private boolean handleCompletedGameIfNeeded(TurnResolutionResult turnResult) {
        Player winner = turnResult.getWinner();
        if (winner == null) {
            return false;
        }

        broadcastFinishedGame(winner);
        resetServerToLobbyMode();
        return true;
    }

    private void broadcastFinishedGame(Player winner) {
        System.out.println("Game over! Winner: " + winner.getName());
        broadcaster.broadcastState(gameState);
        broadcaster.broadcastGameOver(buildWinnerMessage(winner));
    }

    private String buildWinnerMessage(Player winner) {
        return "Game over! Winner: " + winner.getName() + " ("
                + winner.getPrestigePoints() + " points)";
    }

    private void resetServerToLobbyMode() {
        gameStarted = false;
        gameState = null;
        turnManager.resetFinalRound();
        broadcaster.broadcastLobbyState();
    }

    private void logDisconnect() {
        System.out.println(
                "Client disconnected. Remaining: "
                        + lobbyManager.getClientCount()
        );
    }

    private void refreshLobbyIfWaiting() {
        if (!gameStarted) {
            broadcaster.broadcastLobbyState();
        }
    }

    private void shutDownIfLobbyIsEmpty() {
        if (lobbyManager.getClientCount() != 0) {
            return;
        }

        System.out.println("All clients disconnected. Shutting down.");
        closeServerSocketQuietly();
    }

    private void closeServerSocketQuietly() {
        try {
            serverSocket.close();
        } catch (IOException e) {
            // Ignore close failures while the server is already shutting down.
        }
    }
}
